# Site settings
title: Zachary Lester
email: zachary.greg.lester@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Zachary Lester, JavaScript Software Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.zacharylester.com" # the base hostname & protocol for your site
twitter_username: dire_parakeet
github_username:  zlester

# Build settings
markdown: kramdown
